### ISSUE TITLE
@jupyterlab/hub-extension@0.4.1" is not compatible 

### ISSUE THREAD

**Issue by martinorpa** [jupyterhub/jupyterlab-hub#22]
Required  Actual     Package
^0.9.0      ^0.10.0    '@'jupyterlab/application
^0.9.0       ^0.10.0   '@'jupyterlab/apputils
^0.9.0       ^0.10.0   '@'jupyterlab/coreutils

**Comment by blink1073** [comment]
Hi @martinorpa, it looks like you're using JuptyerLab 0.26.  Are you able to upgrade to 0.27?

**Comment by willingc** [comment]
Hi @martinorpa,

I'm going to close this issue as resolved. If you are still having difficulty after upgrading, please let us know. Thanks.
