### ISSUE TITLE
Add top bar override to include hub links

### ISSUE THREAD

**Issue by cam72cam** [jupyterhub/jupyterlab-hub#34]
The default JupyterNotebook interface subclasses the notebook to inject some lab features like a link to the control panel.

See: 
https://github.com/jupyterhub/jupyterhub/blob/master/jupyterhub/singleuser.py#L173

It would seem the same thing needs to be done for the Lab top bar.

I would be happy to work on this if someone could point me in the right direction for where this subclass should be put

**Comment by minrk** [comment]
This is precisely what this jupyterlab-hub package does.

<img width="513" alt="screen shot 2018-01-16 at 11 21 16" src="https://user-images.githubusercontent.com/151929/35007834-820dc314-faaf-11e7-9876-6032894c7d38.png">

If you set:

```python
c.Spawner.cmd = ['jupyter-labhub']
```

it will launch jupyterlab with the hub extension

**Comment by cam72cam** [comment]
Ah ok.  My mistake.

I was expecting a distinct button similar to the older notebook functionality

**Comment by choldgraf** [comment]
no mistake @cam72cam - thanks for pointing this out, we should document it better!
