### ISSUE TITLE
Installation error - fatal: Could not read from remote repository

### ISSUE THREAD

**Issue by VanDavv** [jupyterhub/jupyterlab-hub#43]
I try to install this extension both using docker conttainer and by cloning the repo itself. 

From docker:
```
Step 12/15 : RUN jupyter labextension install @jupyterlab/hub-extension
 ---> Running in bef839415d67
> /usr/bin/npm pack @jupyterlab/hub-extension
npm ERR! git clone git@github.com:jupyterlab/hub-extension Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-jupyterlab-hub-extension-db748e7c'...
npm ERR! git clone git@github.com:jupyterlab/hub-extension Host key verification failed.
npm ERR! git clone git@github.com:jupyterlab/hub-extension fatal: Could not read from remote repository.
npm ERR! git clone git@github.com:jupyterlab/hub-extension 
npm ERR! git clone git@github.com:jupyterlab/hub-extension Please make sure you have the correct access rights
npm ERR! git clone git@github.com:jupyterlab/hub-extension and the repository exists.
npm ERR! addLocal Could not install jupyterlab/hub-extension
npm ERR! Error: ENOENT, stat 'jupyterlab/hub-extension'
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>
```

Locally:
```
$ git clone git@github.com:jupyterlab/hub-extension
Cloning into 'hub-extension'...
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by VanDavv** [comment]
@blink1073 as I said, cloning via ssh also doesn't work
```
Step 13/27 : RUN git clone git@github.com:jupyterlab/jupyterlab-hub /labhub
 ---> Running in 2de10a5f4ebc
Cloning into '/labhub'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists
```
whereas cloning via HTTPS works
```
Step 13/27 : RUN git clone https://github.com/jupyterhub/jupyterlab-hub.git /labhub
 ---> Running in 4ab801732b31
Cloning into '/labhub'...
 ---> 7fc2c6850bf0
Removing intermediate container 4ab801732b31

**Comment by blink1073** [comment]
Does this work then?

```
RUN git clone https://github.com/jupyterhub/jupyterlab-hub.git /labhub
RUN cd jupyterlab-hub
RUN npm install
RUN npm run build
RUN jupyter labextension install .
```

**Comment by VanDavv** [comment]
@blink1073 Yes, it works

**Comment by blink1073** [comment]
I'd recommend using that or looking in to your `node` config to see why it would be attempting to pull from `git` instead of `npm.org`.

**Comment by VanDavv** [comment]
I think it's not dependent on my configuration, since i use Docker containers which installs fresh version of node itself (8.x version). Could You confirm that it works for You on docker?

**Comment by blink1073** [comment]
I am not a docker user, so I'll have to defer, sorry.  I did confirm that `jupyter labextension install @jupyterlab/hub-extension` works in a docker-based environment.

**Comment by gcbgit** [comment]
I'm having the same problem on a Raspberry Pi and freshly installed jupyter, jupyterhub and jupyterlab.

> sudo jupyter labextension install @jupyterlab/hub-extension
> > /usr/bin/npm pack @jupyterlab/hub-extension
> The authenticity of host 'github.com (192.30.255.113)' can't be established.
> RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
> -|e you sure you want to continue connecting (yes/no)? -
> npm ERR! git clone git@github.com:jupyterlab/hub-extension Cloning into bare repository '/root/.npm/_git-remotes/git-github-com-jupyterlab-hub-extension-db748e7c'...
> npm ERR! git clone git@github.com:jupyterlab/hub-extension Host key verification failed.
> npm ERR! git clone git@github.com:jupyterlab/hub-extension fatal: Could not read from remote repository.
> npm ERR! git clone git@github.com:jupyterlab/hub-extension 
> npm ERR! git clone git@github.com:jupyterlab/hub-extension Please make sure you have the correct access rights
> npm ERR! git clone git@github.com:jupyterlab/hub-extension and the repository exists.
> npm ERR! addLocal Could not install jupyterlab/hub-extension
> npm ERR! Error: ENOENT: no such file or directory, stat 'jupyterlab/hub-extension'
> npm ERR!     at Error (native)
> npm ERR! If you need help, you may report this *entire* log,
> npm ERR! including the npm and node versions, at:
> npm ERR!     <http://github.com/npm/npm/issues>
> 
> npm ERR! System Linux 4.9.59+
> npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "pack" "@jupyterlab/hub-extension"
> npm ERR! cwd /tmp/tmpZpRFue
> npm ERR! node -v v4.8.2
> npm ERR! npm -v 1.4.21
> npm ERR! path jupyterlab/hub-extension
> npm ERR! syscall stat
> npm ERR! code ENOENT
> npm ERR! errno -2
> npm ERR! 
> npm ERR! Additional logging details can be found in:
> npm ERR!     /tmp/tmpZpRFue/npm-debug.log
> npm ERR! not ok code 0
> 
> Errored, use --debug for full output:
> ValueError: "@jupyterlab/hub-extension" is not a valid npm package

**Comment by consideRatio** [comment]
## Attempt of an issue summary

Running ...
```
jupyter labextension install @jupyterlab/hub-extension
```
indirectly runs ...
```
/usr/bin/npm pack @jupyterlab/hub-extension
```
indirectly runs ...
```
git clone git@github.com:jupyterlab/hub-extension
```
Resulting in the error...
```
Permission denied (publickey).
fatal: Could not read from remote repository.
```

## Hmmm...
Can't contribute to solving this much... Just made a search and found [the following on stackoverflow question](
https://stackoverflow.com/questions/49475386/git-clone-and-npm-install-permission-denied-publickey) with a similar error:
> This means, on your local machine, you haven't made any SSH keys. Not to worry. Here's how to fix: https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

I don't know what ssh setup the `npm pack` command will utilize or if this relevant =/

**Comment by VanDavv** [comment]
@consideRatio I have on my local machine ssh keys configured, but the error still occurs. Look at [my first comment](https://github.com/jupyterhub/jupyterlab-hub/issues/43#issue-301313027) where I try to download it manyally and the error doesn't mention anything about ssh keys, there's only `ERROR: Repository not found.`

**Comment by dhirschfeld** [comment]
You can force the use of https urls with:
```
git config --global url."https://github.com/".insteadOf git://github.com/ 
git config --global url."https://github.com/".insteadOf git@github.com:
```

**Comment by consideRatio** [comment]
@VanDavv I'm now knowledgeable enough about jupyterlab extensions, but the error of repo not found come when the following command is run:

```
git clone git@github.com:jupyterlab/hub-extension
```

I figure it may be meant to be:

```
git clone git@github.com:jupyterhub/jupyterlab-hub
```

**Comment by deppfx** [comment]
So, the solution is to upgrade your npm. I removed the npm I installed using yum. Then I reinstalled npm using the script provided on the npm website which is:
```curl -sL https://rpm.nodesource.com/setup_10.x | bash -```

**Comment by VanDavv** [comment]
I can confirm that @deppfx solution works!
